// AUTO-GENERATED by tools/printify-merkkipaiva/gen-spec.mjs — do not edit by hand.
// Maps a blog guide slug to age-grouped product slugs. Cards resolve live via useProducts().
export interface GuideRecoGroup {
  title: string;
  slugs: string[];
}

export const guideRecommendations: Record<string, GuideRecoGroup[]> = {
  "lahja-miehelle-30v-40v-50v-60v": [
    {
      "title": "30-vuotiaalle",
      "slugs": [
        "30v-selka-alkaa-jo-rusahdella-t-paita",
        "30v-selka-alkaa-jo-rusahdella-huppari",
        "30v-selka-alkaa-jo-rusahdella-muki",
        "30-ja-liian-vanha-tyhmyyksiin-teen-ne-silti-t-paita",
        "30-ja-liian-vanha-tyhmyyksiin-teen-ne-silti-huppari",
        "30-ja-liian-vanha-tyhmyyksiin-teen-ne-silti-muki"
      ]
    },
    {
      "title": "40-vuotiaalle",
      "slugs": [
        "40v-kunnossa-niinku-20v-t-paita",
        "40v-kunnossa-niinku-20v-huppari",
        "40v-kunnossa-niinku-20v-muki",
        "40-vuotta-henkisesti-18-t-paita",
        "40-vuotta-henkisesti-18-huppari",
        "40-vuotta-henkisesti-18-muki",
        "40v-ei-keski-ika-klassikko-t-paita",
        "40v-ei-keski-ika-klassikko-huppari",
        "40v-ei-keski-ika-klassikko-muki"
      ]
    },
    {
      "title": "50-vuotiaalle",
      "slugs": [
        "50v-puoli-vuosisataa-ei-naarmuakaan-t-paita",
        "50v-puoli-vuosisataa-ei-naarmuakaan-huppari",
        "50v-puoli-vuosisataa-ei-naarmuakaan-muki",
        "50-ja-paras-vasta-tulossa-t-paita",
        "50-ja-paras-vasta-tulossa-huppari",
        "50-ja-paras-vasta-tulossa-muki"
      ]
    },
    {
      "title": "60-vuotiaalle",
      "slugs": [
        "60v-mutta-fyysinen-kunto-kuin-20v-t-paita",
        "60v-mutta-fyysinen-kunto-kuin-20v-huppari",
        "60v-mutta-fyysinen-kunto-kuin-20v-muki",
        "60-vuotta-nuori-t-paita",
        "60-vuotta-nuori-huppari",
        "60-vuotta-nuori-muki",
        "60v-takuu-mennyt-toimii-silti-t-paita",
        "60v-takuu-mennyt-toimii-silti-huppari",
        "60v-takuu-mennyt-toimii-silti-muki"
      ]
    }
  ],
  "lahja-naiselle-30v-40v-50v-60v": [
    {
      "title": "30-vuotiaalle",
      "slugs": [
        "30-nuori-villi-ja-jo-vasynyt-t-paita",
        "30-nuori-villi-ja-jo-vasynyt-huppari",
        "30-nuori-villi-ja-jo-vasynyt-muki",
        "30v-paranen-ian-myota-kuin-viini-t-paita",
        "30v-paranen-ian-myota-kuin-viini-huppari",
        "30v-paranen-ian-myota-kuin-viini-muki"
      ]
    },
    {
      "title": "40-vuotiaalle",
      "slugs": [
        "40v-henkisesti-18-tyylilla-40-t-paita",
        "40v-henkisesti-18-tyylilla-40-huppari",
        "40v-henkisesti-18-tyylilla-40-muki",
        "40-ja-fabulous-t-paita",
        "40-ja-fabulous-huppari",
        "40-ja-fabulous-muki",
        "40v-ei-vanha-vintage-t-paita",
        "40v-ei-vanha-vintage-huppari",
        "40v-ei-vanha-vintage-muki"
      ]
    },
    {
      "title": "50-vuotiaalle",
      "slugs": [
        "50-ja-hopeanhohtoinen-vain-hiukset-t-paita",
        "50-ja-hopeanhohtoinen-vain-hiukset-huppari",
        "50-ja-hopeanhohtoinen-vain-hiukset-muki",
        "50-vuotta-nuori-t-paita",
        "50-vuotta-nuori-huppari",
        "50-vuotta-nuori-muki"
      ]
    },
    {
      "title": "60-vuotiaalle",
      "slugs": [
        "60v-mutta-sydan-kuin-20v-t-paita",
        "60v-mutta-sydan-kuin-20v-huppari",
        "60v-mutta-sydan-kuin-20v-muki",
        "60-vuotta-nuori-ja-nokkela-t-paita",
        "60-vuotta-nuori-ja-nokkela-huppari",
        "60-vuotta-nuori-ja-nokkela-muki",
        "60v-kokenut-ei-vanha-t-paita",
        "60v-kokenut-ei-vanha-huppari",
        "60v-kokenut-ei-vanha-muki"
      ]
    }
  ],
  "hauskimmat-elakelahjat-selviytymisopas": [
    {
      "title": "Eläkkeelle jäävälle",
      "slugs": [
        "elakkeella-kiireinen-tekemaan-ei-mitaan-t-paita",
        "elakkeella-kiireinen-tekemaan-ei-mitaan-huppari",
        "elakkeella-kiireinen-tekemaan-ei-mitaan-muki",
        "virallisesti-tyoton-epavirallisesti-vapaa-t-paita",
        "virallisesti-tyoton-epavirallisesti-vapaa-huppari",
        "virallisesti-tyoton-epavirallisesti-vapaa-muki",
        "40-vuotta-toita-nyt-ikuinen-viikonloppu-t-paita",
        "40-vuotta-toita-nyt-ikuinen-viikonloppu-huppari",
        "40-vuotta-toita-nyt-ikuinen-viikonloppu-muki",
        "elakelainen-aamuheratys-vapaaehtoinen-t-paita",
        "elakelainen-aamuheratys-vapaaehtoinen-huppari",
        "elakelainen-aamuheratys-vapaaehtoinen-muki"
      ]
    }
  ]
};
