export default async function handler(req, res) {
  if (req.method !== 'GET') {
      res.status(405).json({ error: 'Method not allowed' });
          return;
            }

              const products = [
                  {
                        id: 'kalamies-t-paita',
                              title: 'KALAMIES | T-Paita',
                                    description: 'Klassinen puuvillapaita hauskal tekstillä',
                                          price: 24.90,
                                                link: 'https://huumorikauppa.fi/tuote/kalamies-t-paita',
                                                      imageUrl: 'https://huumorikauppa.fi/images/products/kalamies.jpg',
                                                            availability: 'in stock',
                                                                  category: 'T-Paidat'
                                                                      },
                                                                          {
                                                                                id: 'amatimies-t-paita',
                                                                                      title: 'AMATIMIES | T-Paita',
                                                                                            description: 'Hauska t-paita ammatillisille ammattilaisille',
                                                                                                  price: 24.90,
                                                                                                        link: 'https://huumorikauppa.fi/tuote/amatimies-t-paita',
                                                                                                              imageUrl: 'https://huumorikauppa.fi/images/products/amatimies.jpg',
                                                                                                                    availability: 'in stock',
                                                                                                                          category: 'T-Paidat'
                                                                                                                              },
                                                                                                                                  {
                                                                                                                                        id: 'aiti-huppari',
                                                                                                                                              title: 'maailman paras ÄITI | Huppari',
                                                                                                                                                    description: 'Herkkä äideille tarkoitettu huppari',
                                                                                                                                                          price: 49.90,
                                                                                                                                                                link: 'https://huumorikauppa.fi/tuote/maailman-paras-aiti-huppari',
                                                                                                                                                                      imageUrl: 'https://huumorikauppa.fi/images/products/aiti-huppari.jpg',
                                                                                                                                                                            availability: 'in stock',
                                                                                                                                                                                  category: 'Hupparit'
                                                                                                                                                                                      }
                                                                                                                                                                                        ];
                                                                                                                                                                                        
                                                                                                                                                                                          const format = req.query.format || 'xml';
                                                                                                                                                                                          
                                                                                                                                                                                            if (format === 'xml') {
                                                                                                                                                                                                let xml = '<?xml version="1.0" encoding="UTF-8"?>\n';
                                                                                                                                                                                                    xml += '<rss version="2.0" xmlns:g="http://base.google.com/ns/1.0">\n';
                                                                                                                                                                                                        xml += '<channel>\n';
                                                                                                                                                                                                            xml += '<title>Huumorikauppa Product Feed</title>\n';
                                                                                                                                                                                                                xml += '<link>https://huumorikauppa.fi</link>\n';
                                                                                                                                                                                                                    xml += '<description>Finnish humor products</description>\n';
                                                                                                                                                                                                                    
                                                                                                                                                                                                                        products.forEach(product => {
                                                                                                                                                                                                                              xml += '<item>\n';
                                                                                                                                                                                                                                    xml += `<g:id>${escapeXml(product.id)}</g:id>\n`;
                                                                                                                                                                                                                                          xml += `<title>${escapeXml(product.title)}</title>\n`;
                                                                                                                                                                                                                                                xml += `<description>${escapeXml(product.description)}</description>\n`;
                                                                                                                                                                                                                                                      xml += `<g:price>${product.price} EUR</g:price>\n`;
                                                                                                                                                                                                                                                            xml += `<link>${escapeXml(product.link)}</link>\n`;
                                                                                                                                                                                                                                                                  xml += `<g:image_link>${escapeXml(product.imageUrl)}</g:image_link>\n`;
                                                                                                                                                                                                                                                                        xml += `<g:availability>${product.availability}</g:availability>\n`;
                                                                                                                                                                                                                                                                              xml += `<g:product_type>${escapeXml(product.category)}</g:product_type>\n`;
                                                                                                                                                                                                                                                                                    xml += '</item>\n';
                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                            xml += '</channel>\n</rss>';
                                                                                                                                                                                                                                                                                                res.setHeader('Content-Type', 'application/xml; charset=utf-8');
                                                                                                                                                                                                                                                                                                    res.status(200).send(xml);
                                                                                                                                                                                                                                                                                                      } else if (format === 'csv') {
                                                                                                                                                                                                                                                                                                          let csv = 'id,title,description,price,link,image_link,availability,category\n';
                                                                                                                                                                                                                                                                                                              products.forEach(product => {
                                                                                                                                                                                                                                                                                                                    csv += `"${product.id}","${product.title}","${product.description}",${product.price},"${product.link}","${product.imageUrl}","${product.availability}","${product.category}"\n`;
                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                            res.setHeader('Content-Type', 'text/csv; charset=utf-8');
                                                                                                                                                                                                                                                                                                                                res.status(200).send(csv);
                                                                                                                                                                                                                                                                                                                                  } else if (format === 'json') {
                                                                                                                                                                                                                                                                                                                                      res.setHeader('Content-Type', 'application/json; charset=utf-8');
                                                                                                                                                                                                                                                                                                                                          res.status(200).json({ products });
                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                res.status(400).json({ error: 'Invalid format. Use xml, csv, or json' });
                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                  function escapeXml(str) {
                                                                                                                                                                                                                                                                                                                                                    return str.replace(/[<>&'"]/g, char => {
                                                                                                                                                                                                                                                                                                                                                        const chars = {
                                                                                                                                                                                                                                                                                                                                                              '<': '&lt;',
                                                                                                                                                                                                                                                                                                                                                                    '>': '&gt;',
                                                                                                                                                                                                                                                                                                                                                                          '&': '&amp;',
                                                                                                                                                                                                                                                                                                                                                                                "'": '&apos;',
                                                                                                                                                                                                                                                                                                                                                                                      '"': '&quot;'
                                                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                                              return chars[char] || char;
                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                }
